name = "ftcglobal-ca"
pages_build_output_dir = "public"
compatibility_date = "2025-10-29"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "webAgnt-db"
database_id = "6ec3b72b-4dc4-4d9a-9bc6-a5863a81a840"

[vars]
MAX_ROUNDS = "5"
MAX_TOKENS_PER_MESSAGE = "500"

[placement]
mode = "smart"

[env.preview]
  [[env.preview.d1_databases]]
  binding = "DB"
  database_name = "webAgnt-db-staging"
  database_id = "fefdb825-4117-44f2-aef4-39b4de7212c4"